spring.application.name=assessment

# dropbox credentials
dropbox.client-id=YOUR_APP_KEY
dropbox.client-secret=YOUR_APP_SECRET
dropbox.redirect-uri=http://localhost:8080/oauth2/callback
dropbox.scopes=team_info.read
